---
title: "Twitter sentiment"
author: "Mariona"
date: "13/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(twitteR)
library(ROAuth)
library(hms)
library(lubridate) 
library(tidytext)
library(tm)
library(wordcloud)
library(igraph)
library(glue)
library(networkD3)
library(rtweet)
library(plyr)
library(stringr)
library(ggplot2)
library(ggeasy)
library(plotly)
library(dplyr)  
library(hms)
library(lubridate) 
library(magrittr)
library(tidyverse)
library(janeaustenr)
library(widyr)

library(httpuv)
library(rtweet)
```

## Gather Twitter data

https://rpubs.com/shinhaenglee/692598

```{r authorise}

api_key = "XsHAUOWl8A9XFDoZrXIG1tjRi"
api_secret = "xhbxZ26y5oGw5018AY2vuaxAVi08rcYDEWhs4uJOpJZjDvQFGX"

## authentication via web browser
token <- create_token(
  app = "sentiment",
  consumer_key = api_key, 
  consumer_secret = api_secret,
  set_renv = FALSE
  ) 
token

rt <- search_tweets(
  "New Zealand housing", n = 18000, include_rts = FALSE, token = token)
rt2 <- search_tweets('CoreLogic NZ', n = 18000, include_rts = FALSE, token = token)
rt3 <- search_tweets('corelogic NEW Zealand', n = 18000, include_rts = FALSE, token = token)
rt4 <- search_tweets('#nzpol housing', n = 18000, include_rts = FALSE, token = token)
rt5 <- search_tweets('kainga ora', n = 18000, include_rts = FALSE, token = token)

```

## Including Plots

You can also embed plots, for example:

```{r plot_ts}

ts_plot(rt, 'days') 
ts_plot(rt2,'days')
ts_plot(rt3,'days')
ts_plot(rt4, 'days')
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
